# Generated by Django 4.2 on 2026-01-28 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('opis', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('numer_vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)])),
                ('rok_produkcji', models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('kolor', models.CharField(default='Czarny', max_length=50)),
                ('cena_za_dobe', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('data_dodania', models.DateField(default=django.utils.timezone.now)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.kategoria')),
                ('wlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wynajem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_od', models.DateField()),
                ('data_do', models.DateField()),
                ('ilosc_dni', models.PositiveIntegerField()),
                ('laczna_cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.samochod')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WniosekWlasciciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posiada_prawo_jazdy', models.BooleanField(default=False)),
                ('numer_telefonu', models.CharField(default='+48', max_length=12, validators=[django.core.validators.RegexValidator(message="Numer telefonu może zawierać tylko cyfry i opcjonalnie '+' na początku.", regex='^\\+?\\d{9,12}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
