# Generated by Django 4.2 on 2026-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='wynajety',
            field=models.BooleanField(default=False),
        ),
    ]
