# Generated by Django 4.2 on 2026-01-24 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='numer_vin',
            field=models.CharField(blank=True, default='000654372VA700965', max_length=17, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(17)]),
        ),
    ]
