# Generated by Django 4.2 on 2026-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='cena_za_dobe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
