# Generated by Django 4.2 on 2026-01-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wniosekwlasciciel',
            name='regulamin',
            field=models.BooleanField(default=False),
        ),
    ]
