# Generated by Django 4.2 on 2026-01-27 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0002_samochod_wynajety'),
    ]

    operations = [
        migrations.CreateModel(
            name='WniosekWlasciciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('dodatkowe_info', models.TextField(blank=True, null=True)),
                ('data_zlozenia', models.DateTimeField(default=django.utils.timezone.now)),
                ('zatwierdzony', models.BooleanField(default=False)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
