# Generated by Django 4.2 on 2026-01-24 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_alter_samochod_numer_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='numer_vin',
            field=models.CharField(default='zastepczy_vin', max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)]),
            preserve_default=False,
        ),
    ]
