# Generated by Django 4.2 on 2026-01-23 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0002_samochod_cena_za_dobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samochod',
            name='cena_za_dobe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
