# Generated by Django 4.2 on 2026-01-28 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0003_wniosekwlasciciel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='numer_telefonu',
            field=models.CharField(default='+48', max_length=12, validators=[django.core.validators.RegexValidator(message="Numer telefonu może zawierać tylko cyfry i opcjonalnie '+' na początku.", regex='^\\+?\\d{9,12}$')]),
        ),
    ]
