# Generated by Django 4.2 on 2026-01-26 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wypozyczalnia', '0004_userprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wynajem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wynajmu', models.DateField(default=django.utils.timezone.now)),
                ('ilosc_dni', models.PositiveIntegerField(default=1)),
                ('samochod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.samochod')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
