# Generated by Django 4.2 on 2026-01-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0004_alter_userprofil_numer_telefonu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochod',
            name='wynajety',
        ),
    ]
