# Generated by Django 4.2 on 2026-01-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0005_wynajem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wynajem',
            name='data_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wynajem',
            name='data_od',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wynajem',
            name='laczna_cena',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
